config/routes.rb
BidPal::Application.routes.draw do

	
    resources :chat_messages do
		member do
			get :users
		end
	end	
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords", :confirmations => "confirmations"}
  devise_scope :user do

	root :to => "user_sessions#new"			#default page, or first screen of the website
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
	
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  end
  
  resources :users, :user_sessions, :hand_states
  

  

  

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  match 'admin' => 'users#index', :as => :admin
  match 'dealer' => 'hand_states#new', :as => :dealer
  match 'bidding' => 'chat_messages#index', :as => :bidding
  
  match 'tff' => 'hand_states#tff', :as => :tff
  match 'handTypes' => 'hand_states#handTypes', :as => :handTypes
  match 'preview1' => 'hand_states#preview1', :as => :preview1
  match 'preview2' => 'hand_states#preview2', :as => :preview2
  match 'preview3' => 'hand_states#preview3', :as => :preview3
  match 'preview4' => 'hand_states#preview4', :as => :preview4
  
  
  match 'home' => 'hand_states#index', :as => :home
  match 'about_us' => 'user#about_us', :as => :about_us
  match 'contact' => 'user#contact', :as => :contact
  match 'game' => 'user#game', :as => :game
  
  match 'refreshing' => 'chat_messages#refresher', :as => :refreshing
  
 end

app/models/hand_state.rb
class HandState < ActiveRecord::Base
  attr_accessible :bits, :control, :counts, :email, :fl, :fv, :length, :loser, :points, :together, :totalcontrol, :totalcounts, :totalfl, :totalfv, :totalloser, :totalpots
#resourcify
  belongs_to :user
  attr_accessor :current_user
end

app/controllers/hand_states_controller.rb
class HandStatesController < ApplicationController
  # GET /hand_states
  # GET /hand_states.json
  set_tab :dealer
  def index
    @hand_states = HandState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hand_states }
    end
  end

  # GET /hand_states/1
  # GET /hand_states/1.json
  def show
    @hand_state = HandState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand_state }
    end
  end

  # GET /hand_states/new
  # GET /hand_states/new.json
  def new
    @hand_state = HandState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hand_state }
    end
  end

  # GET /hand_states/1/edit
  def edit
    @hand_state = HandState.find(params[:id])
  end

  # POST /hand_states
  # POST /hand_states.json
  def create
    @hand_state = HandState.new(params[:hand_state])

    respond_to do |format|
      if @hand_state.save
        format.html { redirect_to @hand_state, notice: 'Hand state was successfully created.' }
        format.json { render json: @hand_state, status: :created, location: @hand_state }
      else
        format.html { render action: "new" }
        format.json { render json: @hand_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hand_states/1
  # PUT /hand_states/1.json
  def update
    @hand_state = HandState.find(params[:id])

    respond_to do |format|
      if @hand_state.update_attributes(params[:hand_state])
        format.html { redirect_to @hand_state, notice: 'Hand state was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hand_state.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def tff
    @usrData = {} 
    #flash[:notice] = @usrData
    respond_to do |format|
      format.html {render :text => @usrData } 
      
      format.json { render json: @usrData }
    end
 end
 
 def handTypes
    @users = User.where("last_request_at > :Time", :Time => Time.now - 5.hour)
    @users.each do |user|
      @user = user.name
    end
 end
 
def preview1
   
end

def preview2
   
end

def preview3
   
end

def preview4
   
end
 

  # DELETE /hand_states/1
  # DELETE /hand_states/1.json
  def destroy
    @hand_state = HandState.find(params[:id])
    @hand_state.destroy

    respond_to do |format|
      format.html { redirect_to hand_states_url }
      format.json { head :no_content }
    end
  end
  
  def process_input

  end
end

app/helpers/hand_states_helper.rb
module HandStatesHelper
end

app/helpers/handstate_helper.rb
module HandstateHelper
end

app/views/hand_states/_form.html.erb
<%= form_for(@hand_state) do |f| %>
  <% if @hand_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hand_state.errors.count, "error") %> prohibited this hand_state from being saved:</h2>

      <ul>
      <% @hand_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
	<tr>
		<td>
			<div id="tableBox">
			<table id="table-1" cellpadding="20"> 
					
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center" >AND</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">OR</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">+</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">-</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">></p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center"><</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">>=</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center"><=</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">=</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">!=</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">HCP</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">SHAPE</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">CLUB</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">DIAMOND</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">SPADE</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">HEART</p></div></td>
				</tr>
				
				<tr>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">ANY</p></div></td>
					<td onmouseup = dropitem()><div id="tabs2" class="ui-widget-header"> <p align="center">()</p></div></td>
				</tr>
		
			</table>
			</div>
			
		</td>
		<td></td> <td></td> <td></td> <td></td>
		<td>
			<div id="handsBox">
				<p align="center">Generated Hands</p>
			  
			</div>		
		</td>
	</tr>
</table>


<p>Drop Expression Below</p>
<div contenteditable="true">
<table  width="800" height="200" border="1" id="grid">
<tr>
	<td align="center" >
		
	</td>
</tr>	
</table>
</div>


<% end %>

app/views/hand_states/admin.html.erb
<h1>Listing Players</h1>
<p id="notice"> <%= notice %></p>
<table>
  <tr>
    <th>Username</th>
	<th>Email</th>
    <th></th>
   
  </tr>

<% if @user %>
<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
	<td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to "Play", :dealer %>

app/views/hand_states/edit.html.erb
<h1>Editing hand_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @hand_state %> |
<%= link_to 'Back', hand_states_path %>

app/views/hand_states/handTypes.html.erb
  
<div class="headerstyle">
<br></br>
<h1>Bidpal - Basic hand Types</h1>
</div>
<div id="menubar" align="right">
<table>
	<tr>
		<td>
			<%= @user %>
		</td>
		<td>
			<%= link_to "Signout", :logout %>		
		</td>
	</tr>
</table>
	
</div>

<table width="500">
	<tr>
		<td>
			WEST 1N
		</td>
		<td>
			<!-- <%= link_to "Preview", :handTypes, :onclick => "sysAlert(1)" %> -->
			<%= link_to "Preview", preview1_path, :onclick => "window.open(this.href,'preview', 'height=400, width=400');return false;" %>
		</td>
		<td>
			<%= link_to "Select Hand", :bidding %>
		</td> 
	</tr>
	
	<tr>
		<td>
			WEST 1C
		</td>
		<td>
			<%= link_to "Preview", preview2_path, :onclick => "window.open(this.href,'preview', 'height=400, width=400');return false;" %>
		</td>
		<td>
			<%= link_to "Select Hand", :bidding %>
		</td> 
	</tr>
	
	<tr>
		<td>
			WEST 1M
		</td>
		<td>
			
			<%= link_to "Preview", preview3_path, :onclick => "window.open(this.href,'preview', 'height=400, width=400');return false;" %>
		</td>
		<td>
			<%= link_to "Select Hand", :bidding %>
		</td> 
	</tr>
	
	<tr>
		<td>
			WEST SHORT
		</td>
		<td>
			<%= link_to "Preview", preview4_path, :onclick => "window.open(this.href,'preview', 'height=400, width=400');return false;" %>
		</td>
		<td>
			<%= link_to "Select Hand", :bidding %>
		</td> 
	</tr>
</table>

<br /><br />

<%= link_to "New Hand", :dealer %>

  

app/views/hand_states/index.html.erb
<div class="headerstyle">
<br></br>
<h1>Bidpal - The Bridge Bidding practice site</h1>
</div>

<div id="menubar">
<table width="100%">
	<tr>
<td>
	<!--	<%= link_to "Administrator", :admin %>
		<%= link_to "Dealer", :dealer %>                               
 		<%= link_to "Player", :bidding %> -->
	
	<%= tabs_tag :open_tabs => { :id => "tabs", :class => "cool" } do |tab| %>
	  <%= tab.home       'Administrator', :admin, :style => "padding: 20px" %>
	  <%= tab.dashboard  'Dealer', :handTypes, :style => "padding: 20px" %>
	  <%= tab.account    'Player', :bidding %>
	<% end %>	 		
	</td>
	<td align="right">	<%= link_to "Signout", :logout %>
	</td>
	</tr>
	</table>
</div>
<table>
	<tr>
		<td>
			<div id="overviewPanel"> 
			<h2 align="center">Overview</h2>
			<table>
				<tr>
					<td>
						<div id="myHandTypesPanel">
							<h3 align="center"> My Hnad Types</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
							<p>I am feeling good</p>
						</div>
					</td>
				</tr>
					<tr>
					<td>
						<div id="myProjectsPanel">
							<h3 align="center"> My Projects</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
						</div>
				   </td>
				</tr>
				
			</table>
			</div>
		</td>
		
		<td>
			<div id="biddingPanel"> 
			<h2 align="center">Bidding</h2>
			<table>
				<tr>
					<td>
						<div id="yourTurnPanel">
							<h3 align="center"> Your Turn(Partner Has entered the Bid)</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
						</div>
					</td>
				</tr>
					<tr>
					<td>
						<div id="newDealsPanel">
							<h3 align="center"> New Deals</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
						</div>
				   </td>
				</tr>
				
				<tr>
					<td>
						<div id="discussionPanel">
							<h3 align="center"> Discussion</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
						</div>
				   </td>
				</tr>
				
				<tr>
					<td>
						<div id="archivePanel">
							<h3 align="center"> Archive</h3>
							<div id="bottom">
								<%= link_to 'more...', hand_states_path %>
							</div>
						</div>
				   </td>
				</tr>
				
			</table>
			</div>	
		</td>
		
		<td>
			<div id="messagesPanel"> 
			<h2 align="center">Messages</h2>
			</div>
		</td>
	</tr>
</table>

app/views/hand_states/new.html.erb
<div class="headerstyle">
<br></br>
<h1>Bidpal - Create Hand and Generate Deal</h1>
</div>
<div id="menubar" align="right">
	<%= link_to "Signout", :logout %>
</div>

<%= render 'form' %>

<table>
<tr>
<td>
<%= button_to "Back", hand_states_path, :method => "get" %>
</td>
<td>
	 <%= tag "input", { "type" => "button", "data-remote" => "true", "value" => "Generate Deal", "onclick" => "getExpression()" } %> 
</td>

<td>
<%= button_to "Go to Bidding", :bidding, :method => "get" %>
</td>
<td>
	 <%= tag "input", { "type" => "button", "value" => "Next", "onclick" => "getExpression()" } %> 
</td>

</tr>
</table>

app/views/hand_states/preview1.html.erb
<table height="300" width="300" border="1">
	<tr>
		<td>
			<P style="color: #FF9140">NORTH</P>
			<P>5 6 </P>
			<P>4 5 6 J K </P>
			<P>4 5 6 J </P>
			<P>4 5 </P>
		</td>
		<td>
			<P style="color: #FF9140">EAST</P>
			<P>7 8 J Q K </P>
			<P>7 </P>
			<P>7 K </P>
			<P>6 7 J Q K </P>
		</td>
	</tr>
	
	<tr>
		<td>
			<P style="color: #FF9140">WEST</P>
			<P>2 3 4 </P>
			<P>2 3 A </P>
			<P>2 3 Q A </P>
			<P>2 3 A </P>
		</td>
		<td>
			<P style="color: #FF9140">SOUTH</P>
			<P>9 T A </P>
			<P>8 9 T Q </P>
			<P>8 9 T </P>
			<P>8 9 T </P>
		</td>
	</tr>
</table>

app/views/hand_states/preview2.html.erb
<table height="300" width="300" border="1">
	<tr>
		<td>
			<P style="color: #FF9140">NORTH</P>
			<P>A 9 8 5 </P>
			<P>T 5</P>
			<P>3 </P>
			<P>A 9 8 5 4 3 </P>
		</td>
		<td>
			<P style="color: #FF9140">EAST</P>
			<P>Q T </P>
			<P>K 9 4 3 </P>
			<P>J T 7 6 2 </P>
			<P>K Q </P>
		</td>
	</tr>
	
	<tr>
		<td>
			<P style="color: #FF9140">WEST</P>
			<P>K J 3 </P>
			<P>A Q 7 2 </P>
			<P>A Q 9 5 4 </P>
			<P>J </P>
		</td>
		<td>
			<P style="color: #FF9140">SOUTH</P>
			<P>7 6 4 2 </P>
			<P>J 8 6 </P>
			<P>K 8 </P>
			<P>T 7 6 2 </P>
		</td>
	</tr>
</table>

app/views/hand_states/preview3.html.erb
<table height="300" width="300" border="1">
	<tr>
		<td>
			<P style="color: #FF9140">NORTH</P>
			<P>A T 5 4 </P>
			<P>Q 6 </P>
			<P>Q T 5 </P>
			<P>A 9 8 6 </P>
		</td>
		<td>
			<P style="color: #FF9140">EAST</P>
			<P>K 8 7 </P>
			<P>J T 5 </P>
			<P>8 6 3 </P>
			<P>K T 7 2 </P>
		</td>
	</tr>
	
	<tr>
		<td>
			<P style="color: #FF9140">WEST</P>
			<P>Q J 2 </P>
			<P>K 9 8 4 3 </P>
			<P>A J 4 2 </P>
			<P>5 </P>
		</td>
		<td>
			<P style="color: #FF9140">SOUTH</P>
			<P>9 6 3 </P>
			<P>A 7 2 </P>
			<P>K 9 7 </P>
			<P>Q J 4 3 </P>
		</td>
	</tr>
</table>

app/views/hand_states/preview4.html.erb
<table height="300" width="300" border="1">
	<tr>
		<td>
			<P style="color: #FF9140">NORTH</P>
			<P>A J 4 3 </P>
			<P>J 4 </P>
			<P>A Q 7 </P>
			<P>8 7 4 2 </P>
		</td>
		<td>
			<P style="color: #FF9140">EAST</P>
			<P>T 9 </P>
			<P>Q 6 3 </P>
			<P>K 9 8 5 2 </P>
			<P>Q J 3 </P>
		</td>
	</tr>
	
	<tr>
		<td>.l
			<P style="color: #FF9140">WEST</P>
			<P>K Q 6 5 </P>
			<P>A T 9 7 5 </P>
			<P>6 4 3 </P>
			<P>T </P>
		</td>
		<td>
			<P style="color: #FF9140">SOUTH</P>
			<P>8 7 2 </P>
			<P>K 8 2 </P>
			<P>J T </P>
			<P>A K 9 6 5 </P>
		</td>
	</tr>
</table>

app/views/hand_states/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_hand_state_path(@hand_state) %> |
<%= link_to 'Back', hand_states_path %>

app/views/hand_states/tff.html.erb
<h1> tff site</h1>