config/routes.rb
BidPal::Application.routes.draw do

	
    resources :chat_messages do
		member do
			get :users
		end
	end	
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords", :confirmations => "confirmations"}
  devise_scope :user do

	root :to => "user_sessions#new"			#default page, or first screen of the website
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
	
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  end
  
  resources :users, :user_sessions, :hand_states
  

  

  

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  match 'admin' => 'users#index', :as => :admin
  match 'dealer' => 'hand_states#new', :as => :dealer
  match 'bidding' => 'chat_messages#index', :as => :bidding
  
  match 'tff' => 'hand_states#tff', :as => :tff
  match 'handTypes' => 'hand_states#handTypes', :as => :handTypes
  match 'preview1' => 'hand_states#preview1', :as => :preview1
  match 'preview2' => 'hand_states#preview2', :as => :preview2
  match 'preview3' => 'hand_states#preview3', :as => :preview3
  match 'preview4' => 'hand_states#preview4', :as => :preview4
  
  
  match 'home' => 'hand_states#index', :as => :home
  match 'about_us' => 'user#about_us', :as => :about_us
  match 'contact' => 'user#contact', :as => :contact
  match 'game' => 'user#game', :as => :game
  
  match 'refreshing' => 'chat_messages#refresher', :as => :refreshing
  
 end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  attr_accessible :date, :message, :name
  belongs_to :user
  attr_accessor :current_user
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  # GET /chat_messages
  # GET /chat_messages.json
  set_tab :bidding
  def index
    @chat_messages = ChatMessage.all
	  @chat_message = ChatMessage.new
	  #@users = User.find(:all, :conditions => ["current_sign_in_at > last_request_at =?" , true])
	  @users = User.where("last_request_at > :Time", :Time => Time.now - 5.hour)
	  @user = User.new

	  #@users = User.logged_in.all
	  #@user = User.find(34)
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chat_messages }
    end
  end

   def refresher
	 @chat_messages = ChatMessage.all
	 @chat_message = ChatMessage.new
	  #@user = User.find(34)
	  
      respond_to do |format|
      format.html 
      format.json { render json: @chat_messages }
    end
  end
  
  # GET /chat_messages/1
  # GET /chat_messages/1.json
  def show
    @chat_message = ChatMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chat_message }
    end
  end

  # GET /chat_messages/new
  # GET /chat_messages/new.json
  def new
    @chat_message = ChatMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chat_message }
    end
  end

  # GET /chat_messages/1/edit
  def edit
    @chat_message = ChatMessage.find(params[:id])
  end

  # POST /chat_messages
  # POST /chat_messages.json
  def create
    @chat_message = ChatMessage.new(params[:chat_message])
	#@chat_message.name = session[:current_user_id]
	
	 respond_to do |format|
      if @chat_message.save
        format.html { redirect_to :bidding }
        format.json { render json: @chat_message, status: :created, location: @chat_message }
      else
        format.html { render action: "new" }
        format.json { render json: @chat_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chat_messages/1
  # PUT /chat_messages/1.json
  def update
    @chat_message = ChatMessage.find(params[:id])

    respond_to do |format|
      if @chat_message.update_attributes(params[:chat_message])
        format.html { redirect_to @chat_message, notice: 'Chat message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chat_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_messages/1
  # DELETE /chat_messages/1.json
  def destroy
    @chat_message = ChatMessage.find(params[:id])
    @chat_message.destroy

    respond_to do |format|
      format.html { redirect_to chat_messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def chat_message_mapping
    @chat_message_mapping ||= chat_message.mappings[:user]
  end
end

app/views/chat_messages/_form.html.erb
<%= form_for([current_user, @chat_message]) do |f| %>
  <% if @chat_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat_message.errors.count, "error") %> prohibited this chat_message from being saved:</h2>

      <ul>
      <% @chat_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
	<table cellspacing = 3>
	<tr>
	<td>
	 <div class="field">
	 <%= f.hidden_field :name, :value => session[:name] %>
	 <%= f.text_field :message, :size => 42 %>
  </div>
  </td>
   <td>
   <div class="actions">
    <%= f.submit "Send" %>
    </div>
	</td>
	</tr>
	</table>
	
   

<% end %>

app/views/chat_messages/bidding.html.erb
<%= render 'index' %>

app/views/chat_messages/edit.html.erb
<h1>Editing chat_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat_message %> |
<%= link_to 'Back', chat_messages_path %>

app/views/chat_messages/index.html.erb
<div class="headerstyle">
<br></br>
<h1>Bidpal - Bid To Win</h1>
</div>

<div id="menubar" align="right">
	<%= link_to "Signout", :logout %>
</div>


<table>
	<tr>
		<td>
			<h2> Online Users </h2>
		</td>
		<td>
			<h2> Chatter box </h2>
		</td>
			
	</tr>
	
	<tr>
		<td>
			<div class="editable2">
				<table width = "100" style="table-layout:fixed" >
					<% if @user %>
					<% @users.each do |user| %>
					<tr>						
						<td>
						<%= user.username %>
						</td>
						<td>
							</td>
					</tr> 
					<% end %>
					<% end %>
				</table>
			</div>
		</td>
			
		<td>
			
		<div id="TextEdit" class="editable">
			<table width = "320" style="table-layout:fixed" >
				    <% if @chat_message %>
						<% @chat_messages.each do |chat_message| %>
							<tr>
							 <td><%= chat_message.name %></td>
							 <td align = right><div style="word-wrap: break-word;"><%= chat_message.message %></div></td>	
							</tr>		
						<% end %>
					<% end %>
					
				</table>
		</div>
	</td>
 </tr>
 
 <tr>
 	<td>
 		<table>
 			<tr>
 				<td>
 					<%= button_to "Dealer", :dealer, :method => "get" %>
 				</td>
 				<td>
 					<%= button_to "Home", hand_states_path, :method => "get" %>
 				</td>
 			</tr>
		</table> 					
 	</td>
 	<td>
 		<script type="text/javascript">
			setTimeout(function() {Ajax();}, 30000);
		</script>
 
		<%= render 'form' %>

 	</td>
 </tr>
</table>

app/views/chat_messages/new.html.erb
<div id="nav" align="right">
	<%= link_to "Signout", :logout %>
</div>
<h1>New chat_message</h1>

<%= render 'form' %>

<%= button_to "Back", hand_states_path, :method => "get" %>

app/views/chat_messages/refresher.html.erb
<div id="TextEdit">
	<table width = "320" style="table-layout:fixed" >
    <% if @chat_message %>
	<% @chat_messages.each do |chat_message| %>
	<tr>
	 <td><%= chat_message.name %></td>
	 <td align = right><div style="word-wrap: break-word;"><%= chat_message.message %></div></td>	
	</tr>
	<br />

	<% end %>
	<% end %>
	</table>
</div>

app/views/chat_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chat_message.name %>
</p>

<p>
  <b>Date:</b>
  <%= @chat_message.date %>
</p>

<p>
  <b>Message:</b>
  <%= @chat_message.message %>
</p>


<%= link_to 'Edit', edit_chat_message_path(@chat_message) %> |
<%= link_to 'Back', chat_messages_path %>