config/routes.rb
BidPal::Application.routes.draw do

	
    resources :chat_messages do
		member do
			get :users
		end
	end	
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords", :confirmations => "confirmations"}
  devise_scope :user do

	root :to => "user_sessions#new"			#default page, or first screen of the website
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
	
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  end
  
  resources :users, :user_sessions, :hand_states
  

  

  

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  match 'admin' => 'users#index', :as => :admin
  match 'dealer' => 'hand_states#new', :as => :dealer
  match 'bidding' => 'chat_messages#index', :as => :bidding
  
  match 'tff' => 'hand_states#tff', :as => :tff
  match 'handTypes' => 'hand_states#handTypes', :as => :handTypes
  match 'preview1' => 'hand_states#preview1', :as => :preview1
  match 'preview2' => 'hand_states#preview2', :as => :preview2
  match 'preview3' => 'hand_states#preview3', :as => :preview3
  match 'preview4' => 'hand_states#preview4', :as => :preview4
  
  
  match 'home' => 'hand_states#index', :as => :home
  match 'about_us' => 'user#about_us', :as => :about_us
  match 'contact' => 'user#contact', :as => :contact
  match 'game' => 'user#game', :as => :game
  
  match 'refreshing' => 'chat_messages#refresher', :as => :refreshing
  
 end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
	
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]  	end
    def persisted?
    false
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 
  def new
    @user_session = UserSession.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render xml: @user_session }
    end
  end

  
  def create
    @user_session = UserSession.new(params[:user_session])
	session[:name] = @user_session.username
    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:hand_states, :notice => 'Login Successful') }
        format.xml { render xml: @user_session, status: :created, :location => @user_session }
      else
        format.html { render action: "new" }
        format.xml { render xml: @user_session.errors, status => :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    #@user = User.find(current_user_id)
    #@user.update_attribute(:last_sign_out_at, Time.now)
    respond_to do |format|
      format.html { redirect_to(:login, :notice => 'GoodBye!') }
      flash[:notice] = "good bye"
      format.xml { head :ok }
    end
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper

end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %> 
 <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Bidpal - The Bridge Bidding practice site</h1>
<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if @user_session %>
<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New User session', :login %>

app/views/user_sessions/new.html.erb
<div class="headerstyle">
<br></br>
<h1>Bidpal - The Bridge Bidding practice site</h1>

</div>
<div id="menubar" align="right">
	<%= link_to "Not a member? Register Here", new_user_path %>
</div>

<table width=800>
<tr>
<td>
<h2>New Player Session</h2>
</td>
<td>
<h2> What is this site about?</h2>
</td>
<tr>
<td>
<%= render 'form' %>
</td>
<td>
<p>This is the place where you can practice bidding. </p>
<p>By logging into the site you can create custom Hands.</p>
<p>And you can practice bidding with  your partner. </p>
<h2>             Happy Bidding !!</h2>

</td>
</tr>
</table>

<div id="footer"> Copyright 2013 by The Bridgers. All Rights Reserved.</div> 

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>